---
- hosts: s6
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  become: yes
  become_user: www-data
  tasks:
    - name: copy local uploads directory to remote
      synchronize:
        src: "{{ playbook_dir }}/../../web/uploads"
        dest: "{{ vhost_path }}/shared/web/uploads/"
