# Liip Imagine
liip_imagine:
    loaders:
       default:
          filesystem:
            locator: filesystem_insecure
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        60x60:
            quality: 95
            filters:
                thumbnail: { size: [ 60, 60 ],    mode: outbound }
        256x256:
            quality: 95
            filters:
                thumbnail: { size: [ 256, 256 ],  mode: outbound }
        250xY:
            quality: 90
            filters:
                thumbnail: { size: [ 250, null ], mode: outbound }
        390xY:
            quality: 90
            filters:
                thumbnail: { size: [ 390, null ], mode: outbound }
        350xY:
            quality: 90
            filters:
                thumbnail: { size: [ 350, null ], mode: outbound }
        480xY:
            quality: 85
            filters:
                thumbnail: { size: [ 480, null ], mode: outbound }
        480x640:
            quality: 85
            filters:
                thumbnail: { size: [ 480, 640 ], mode: inbound }
        700x495:
            quality: 85
            filters:
                thumbnail: { size: [ 700, 495 ], mode: inbound }
        1140x684:
            quality: 85
            filters:
                thumbnail: { size: [ 1140, 684 ], mode: outbound }
        1200xY:
            quality: 85
            filters:
                thumbnail: { size: [ 1200, null ], mode: outbound }
        2300xY:
            quality: 85
            filters:
                thumbnail: { size: [ 2300, null ], mode: outbound }

# Vich Uploader
vich_uploader:
    db_driver: orm
    mappings:
        service:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/services
            upload_destination: "%kernel.root_dir%/../web/uploads/services"
        project:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/projects
            upload_destination: "%kernel.root_dir%/../web/uploads/projects"
        partner:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/partners
            upload_destination: "%kernel.root_dir%/../web/uploads/partners"
        post:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/posts
            upload_destination: "%kernel.root_dir%/../web/uploads/posts"
