app_frontend:
    resource: "@AppBundle/Controller/Front"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    options: { i18n: false }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    options: { i18n: false }

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    options: { i18n: false }

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
    options: { i18n: false }

app_backend:
    resource: "@AppBundle/Controller/Back/"
    type:     annotation

_redirecting_trailing_slashes:
    resource: "@AppBundle/Controller/RedirectingController.php"
    type:     annotation
    options:  { i18n: false }
