services:
# App
    app.google_maps_service:
        class: AppBundle\Service\GoogleMapsService
        arguments: [ "%locale%" ]
# Messaging
    app.courier:
        class: AppBundle\Service\CourierService
        arguments: [ "@swiftmailer.mailer" ]
    app.notification:
        class: AppBundle\Service\NotificationService
        arguments: [ "@app.courier", "@twig", "%mailer_destination%", "%mailer_url_base%" ]
# Repositories
    app.repository.contact_newsletter:
        class: AppBundle\Repository\ContactNewsletterRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - "AppBundle:ContactNewsletter"
# Managers
    app.contact_newsletter_manager:
        class: AppBundle\Manager\ContactNewsletterManager
        arguments:
            - "@app.repository.contact_newsletter"
### Admin
    admin.projects_project:
        class: AppBundle\Admin\ProjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Web", label: "Projecte" }
        arguments:
            - ~
            - AppBundle\Entity\Project
            - AppBundle:Back\ProjectAdmin
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    admin.projects_image:
        class: AppBundle\Admin\ProjectImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Web", label: "Imatge", show_in_dashboard: false }
        arguments:
            - ~
            - AppBundle\Entity\ProjectImage
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    admin.services_service:
        class: AppBundle\Admin\ServiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Web", label: "Servei" }
        arguments:
            - ~
            - AppBundle\Entity\Service
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    admin.partners_partner:
        class: AppBundle\Admin\PartnerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Web", label: "Equip" }
        arguments:
            - ~
            - AppBundle\Entity\Partner
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    admin.blog_tag:
        class: AppBundle\Admin\BlogTagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Blog", label: "Etiqueta" }
        arguments:
            - ~
            - AppBundle\Entity\BlogTag
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    admin.blog_post:
        class: AppBundle\Admin\BlogPostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Blog", label: "Article" }
        arguments:
            - ~
            - AppBundle\Entity\BlogPost
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    admin.contactmessage:
        class: AppBundle\Admin\ContactMessageAdmin
        arguments:
            - ~
            - AppBundle\Entity\ContactMessage
            - AppBundle:Back\ContactMessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Missatge", group: "Contactes" }
    admin.contactnewsletter:
        class: AppBundle\Admin\ContactNewsletterAdmin
        arguments:
            - ~
            - AppBundle\Entity\ContactNewsletter
            -
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Newsletter", group: "Contactes" }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Usuari", group: "Usuaris" }
# Twig
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
