services:
# App
    app.google_maps_service:
        class: AppBundle\Service\GoogleMapsService
        arguments: [ "%locale%" ]
# Messaging
    app.courier:
        class: AppBundle\Service\CourierService
        arguments: [ "@swiftmailer.mailer" ]
    app.notification:
        class: AppBundle\Service\NotificationService
        arguments: [ "@app.courier", "@twig", "%mailer_destination%", "%mailer_url_base%" ]
# Repositories
    app.repository.contact_newsletter:
        class: AppBundle\Repository\ContactNewsletterRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - "AppBundle:ContactNewsletter"
# Managers
    app.contact_newsletter_manager:
        class: AppBundle\Manager\ContactNewsletterManager
        arguments: [ "@app.repository.contact_newsletter" ]
    app.mailchimp_manager:
        class: AppBundle\Manager\MailchimpManager
        arguments: [ "@mailchimp", "@app.notification" ]
# Menu
    app.frontend_menu_builder:
        class: AppBundle\Menu\FrontendMenuBuilder
        arguments: [ "@knp_menu.factory", "@security.authorization_checker", "@router" ]
    app.frontend_top_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createTopMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: top }
### Admin
    admin.projects_project:
        class: AppBundle\Admin\ProjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Web", label: "Projecte" }
        arguments:
            - ~
            - AppBundle\Entity\Project
            - AppBundle:Back\ProjectAdmin
    admin.projects_image:
        class: AppBundle\Admin\ProjectImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Web", label: "Imatge", show_in_dashboard: false }
        arguments:
            - ~
            - AppBundle\Entity\ProjectImage
            - ~
    admin.services_service:
        class: AppBundle\Admin\ServiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Web", label: "Servei" }
        arguments:
            - ~
            - AppBundle\Entity\Service
            - ~
    admin.partners_partner:
        class: AppBundle\Admin\PartnerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Web", label: "Equip" }
        arguments:
            - ~
            - AppBundle\Entity\Partner
            - ~
    admin.blog_tag:
        class: AppBundle\Admin\BlogTagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Blog", label: "Etiqueta" }
        arguments:
            - ~
            - AppBundle\Entity\BlogTag
            - ~
    admin.blog_post:
        class: AppBundle\Admin\BlogPostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Blog", label: "Article" }
        arguments:
            - ~
            - AppBundle\Entity\BlogPost
            - ~
    admin.contactmessage:
        class: AppBundle\Admin\ContactMessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Missatge", group: "Contactes" }
        arguments:
            - ~
            - AppBundle\Entity\ContactMessage
            - AppBundle:Back\ContactMessageAdmin
    admin.contactnewsletter:
        class: AppBundle\Admin\ContactNewsletterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Newsletter", group: "Contactes" }
        arguments:
            - ~
            - AppBundle\Entity\ContactNewsletter
            -
    admin.user:
        class: AppBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Usuari", group: "Usuaris" }
        arguments:
            - ~
            - AppBundle\Entity\User
            - ~
            - "@fos_user.user_manager"
# Sitemap
    app.sitemap:
        class: AppBundle\Listener\SitemapListener
        arguments: [ "@router", "@doctrine.orm.entity_manager" ]
        tags: [ { name: "presta.sitemap.listener" } ]
# Twig
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
