services:
# Admin
    sonata.admin.services_category:
        class: AppBundle\Admin\ServiceCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Serveis", label: "Categoria" }
        arguments:
            - ~
            - AppBundle\Entity\ServiceCategory
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.services_service:
        class: AppBundle\Admin\ServiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Serveis", label: "Servei" }
        arguments:
            - ~
            - AppBundle\Entity\Service
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.projects_project:
        class: AppBundle\Admin\ProjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Projectes", label: "Projecte" }
        arguments:
            - ~
            - AppBundle\Entity\Project
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
