services:
### Admin
    sonata.admin.services_category:
        class: AppBundle\Admin\ServiceCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Serveis", label: "Categoria" }
        arguments:
            - ~
            - AppBundle\Entity\ServiceCategory
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.services_service:
        class: AppBundle\Admin\ServiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Serveis", label: "Servei" }
        arguments:
            - ~
            - AppBundle\Entity\Service
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.projects_project:
        class: AppBundle\Admin\ProjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Projectes", label: "Projecte" }
        arguments:
            - ~
            - AppBundle\Entity\Project
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.projects_image:
        class: AppBundle\Admin\ProjectImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Projectes", label: "Imatge", show_in_dashboard: false }
        arguments:
            - ~
            - AppBundle\Entity\ProjectImage
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.partners_partner:
        class: AppBundle\Admin\PartnerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Equip", label: "Col·laborador" }
        arguments:
            - ~
            - AppBundle\Entity\Partner
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.blog_tag:
        class: AppBundle\Admin\BlogTagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Blog", label: "Etiqueta" }
        arguments:
            - ~
            - AppBundle\Entity\BlogTag
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.blog_post:
        class: AppBundle\Admin\BlogPostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Blog", label: "Article" }
        arguments:
            - ~
            - AppBundle\Entity\BlogPost
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
