services:
# Mailer
    app.manager.mail:
        class: AppBundle\Manager\MailManager
        arguments:
            - @templating
            - @mailer
### Admin
    sonata.admin.projects_project:
        class: AppBundle\Admin\ProjectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Web", label: "Projecte" }
        arguments:
            - ~
            - AppBundle\Entity\Project
            - AppBundle:Back\ProjectAdmin
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.projects_image:
        class: AppBundle\Admin\ProjectImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Web", label: "Imatge", show_in_dashboard: false }
        arguments:
            - ~
            - AppBundle\Entity\ProjectImage
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.services_service:
        class: AppBundle\Admin\ServiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Web", label: "Servei" }
        arguments:
            - ~
            - AppBundle\Entity\Service
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.partners_partner:
        class: AppBundle\Admin\PartnerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Web", label: "Equip" }
        arguments:
            - ~
            - AppBundle\Entity\Partner
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.blog_tag:
        class: AppBundle\Admin\BlogTagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Blog", label: "Etiqueta" }
        arguments:
            - ~
            - AppBundle\Entity\BlogTag
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.blog_post:
        class: AppBundle\Admin\BlogPostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Blog", label: "Article" }
        arguments:
            - ~
            - AppBundle\Entity\BlogPost
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
